server:
  port: 8081
  tomcat:
    max-threads: 200
    min-spare-threads: 50

spring:
  application:
    name: eureka-server
  profiles:
    active: development
  security:
    user:
      name: admin
      password: 27112003
  cloud:
    config:
      enabled: false

# Eureka Server Configuration
eureka:
  instance:
    hostname: localhost
    appname: eureka-server
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
  server:
    enable-self-preservation: true
    renewal-percent-threshold: 0.85
    eviction-interval-timer-in-ms: 60000
    response-cache-update-interval-ms: 30000
    peer-node-read-timeout-ms: 200
    wait-time-in-ms-when-sync-empty: 1000
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://admin:eureka@123@localhost:8081/eureka/
    registry-fetch-interval-seconds: 5
    initial-instance-info-replication-interval-seconds: 10
    instance-info-replication-interval-seconds: 15

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, env
      base-path: /manage
  endpoint:
    health:
      show-details: always
      show-components: always
    metrics:
      enabled: true
  info:
    env:
      enabled: true

# Logging
logging:
  level:
    com.netflix.eureka: INFO
    com.netflix.discovery: INFO
    org.springframework.cloud.netflix.eureka: DEBUG
  file:
    name: D:\e-commerce\eureka
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"